### ISSUE TITLE
Add Token Auth to Server Authentication

### ISSUE THREAD

**Issue by DylanZeller** [2020SE691T2/RecessAPI#11]

**Comment by jonathanmcdaniel** [comment]
2 Rows need to be added to the database table for users:
"is_staff" is of a boolean type
"is_superuser" is of a boolean type

These are used for django built-in auth, and will allow us to manage accounts through the django backend UI as well.
They will be defaulted to False, unless is the case of the superuser created with the command line for django.

**Comment by DylanZeller** [comment]
Merged to main
